version: "3"

services:
  # django container
  django:
    container_name: backend # 컨테이너명
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: python3 ./backend/manage.py runserver 0:8000
    volumes:
      - ./backend:/app
  web:  # web container
    # 프론트 앱 설정
    container_name: frontend # 컨테이너명
    build: 
      context: ./frontend
      # docekr build 명령을 수행할 경로
      dockerfile: Dockerfile # 실행할 Dockerfile의 경로
    ports: 
      - "3000:3000"
    environment:
      # 환경 변수로 포트 설정을 해준다.
      - PORT=3000
    depends_on: # web 이미지에 대한 컨테이너는 redis, db, django가 생성되고, 시작되기 전에는 빌드되지 않음.
      - django
  nginx:
    # nginx 설정
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - web